name: dockertp

include:
  - dockerServer/docker-compose.yml

services:
  front:
    build:
      context: ./dockerJs
    ports:
      - "80:80"
    depends_on:
      - tomcat
    restart: unless-stopped
